server:
    port: 8080

spring:
    session:
        timeout: 604800
        storeType: HASH_MAP
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 3600000
        validationQuery: SELECT 1
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
        properties:
            hibernate:
                globally_quoted_identifiers: true
                dialect: org.hibernate.dialect.MySQL5Dialect
                proc:
                    param_null_passing: true
